### ISSUE TITLE
Build broken in master

### ISSUE THREAD

**Issue by sgiannoulis** [facebook/openr#100]
_Please use this template for reporting suspected bugs or requests for help._

# Issue Description
Build script fails in building fb303
# Environment
Ubuntu 18.04
master branch  (e7ecdf2ae58b565011929283164734ea72649c0f)

# Minimal test code / Steps to reproduce the issue
run the build_openr.sh script
# What's the actual result?
/tmp/fbcode_builder_getdeps-ZusersZsgiannouZopenrZbuildZfbcode_builder-root/repos/github.com-facebookincubator-fb303.git/fb303/detail/QuantileStatWrappers-inl.h:60:37: error: ‘make_hazard_pointer’ is not a member of ‘folly’
   folly::hazptr_holder<> h = folly::make_hazard_pointer<>();
                                     ^~~~~~~~~~~~~~~~~~~
/tmp/fbcode_builder_getdeps-ZusersZsgiannouZopenrZbuildZfbcode_builder-root/repos/github.com-facebookincubator-fb303.git/fb303/detail/QuantileStatWrappers-inl.h:60:57: error: expected primary-expression before ‘>’ token
   folly::hazptr_holder<> h = folly::make_hazard_pointer<>();
                                                         ^
/tmp/fbcode_builder_getdeps-ZusersZsgiannouZopenrZbuildZfbcode_builder-root/repos/github.com-facebookincubator-fb303.git/fb303/detail/QuantileStatWrappers-inl.h:60:59: error: expected primary-expression before ‘)’ token
   folly::hazptr_holder<> h = folly::make_hazard_pointer<>();
                                                           ^
/tmp/fbcode_builder_getdeps-ZusersZsgiannouZopenrZbuildZfbcode_builder-root/repos/github.com-facebookincubator-fb303.git/fb303/detail/QuantileStatWrappers-inl.h:61:19: error: ‘class folly::hazptr_holder<>’ has no member named ‘protect’
   auto mapPtr = h.protect(stats_);
                   ^~~~~~~
/tmp/fbcode_builder_getdeps-ZusersZsgiannouZopenrZbuildZfbcode_builder-root/repos/github.com-facebookincubator-fb303.git/fb303/detail/QuantileStatWrappers-inl.h:78:16: error: ‘class folly::hazptr_holder<>’ has no member named ‘protect’
     mapPtr = h.protect(stats_);
                ^~~~~~~
/tmp/fbcode_builder_getdeps-ZusersZsgiannouZopenrZbuildZfbcode_builder-root/repos/github.com-facebookincubator-fb303.git/fb303/detail/QuantileStatWrappers-inl.h:83:5: error: ‘class folly::hazptr_holder<>’ has no member named ‘reset_protection’; did you mean ‘get_protected’?
   h.reset_protection();

# What's the expected result?
Finalize build and have openr operational.

**Comment by cooperlees** [comment]
So the build seems to build for me in Docker. Just thrift errors when trying to build the `breeze` cli's thrift 'py3' extensions.
```
Step 11/15 : RUN cd /src && build/build_breeze.sh
 ---> Running in 7e9e3e768132
[FAILURE:openr-thrift/openr/if/OpenrConfig.thrift:16] Could not find include file configerator/structs/neteng/config/vip_service_config.thrift
Traceback (most recent call last):
  File "/src/build/gen.py", line 65, in <module>
    generate_thrift_files()
  File "/src/build/gen.py", line 47, in generate_thrift_files
    check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/facebook/fbthrift/bin/thrift1', '--gen', 'mstch_cpp2', '-I', 'openr-thrift', '-I', 'fb303-thrift', '-I', 'fbzmq-thrift', '-I', 'neteng-thrift', '-I', 'fbthrift-thrift', '-I', '.', '-o', 'openr-thrift/openr/if', 'openr-thrift/openr/if/OpenrConfig.thrift']' returned non-zero exit status 1.
build/build_breeze.sh: line 62: /src/fbthrift-thrift/gen-cpp2/metadata_metadata.h: No such file or directory
build/build_breeze.sh: line 63: /src/fbthrift-thrift/gen-cpp2/metadata_types.h: No such file or directory
build/build_breeze.sh: line 64: /src/fbthrift-thrift/gen-cpp2/metadata_types_custom_protocol.h: No such file or directory
```

Will try find some time to work this out ...
