### ISSUE TITLE
Breeze crashed at runtime on invocation

### ISSUE THREAD

**Issue by Vijayendra-Pretlist** [facebook/openr#46]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue Description
vijayendra@vijayendra-VirtualBox:~/openr/build$ breeze 
Traceback (most recent call last):
  File "/usr/local/bin/breeze", line 9, in <module>
    load_entry_point('py-openr==1.0', 'console_scripts', 'breeze')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/openr/cli/breeze.py", line 22, in <module>
  File "build/bdist.linux-x86_64/egg/openr/cli/clis/config.py", line 14, in <module>
  File "/usr/local/lib/python2.7/dist-packages/py_openr-1.0-py2.7.egg/openr/cli/commands/config.py", line 23
    def _run(self, client: OpenrCtrl.Client):
                         ^
SyntaxError: invalid syntax

# Environment

Ubuntu Desktop-16.04

* tag or commit hash on which this occured

* OS version: <e.g. ubuntu-16.04>
Ubuntu Desktop-16.04

# Minimal test code / Steps to reproduce the issue
vijayendra@vijayendra-VirtualBox:~/openr/build$ breeze 

# What's the actual result?
<include assertion message or callstack if applicable>
breeze crashed at runtime

# What's the expected result?

Usage: breeze [OPTIONS] COMMAND [ARGS]...

  Command line tools for OpenR.
Options:
  -H, --host TEXT               Host to connect to (default = localhost)
  -t, --timeout INTEGER         Timeout for socket communication in ms
  -f, --ports-config-file TEXT  JSON file for ports config
  --color / --no-color          Enable coloring display
  --help                        Show this message and exit.

Commands:
  config         CLI tool to peek into Config Store module.
  decision       CLI tool to peek into Decision module.
  fib            CLI tool to peek into Fib module.
  healthchecker  CLI tool to peek into Health Checker module.
  kvstore        CLI tool to peek into KvStore module.
  lm             CLI tool to peek into Link Monitor module.
  monitor        CLI tool to peek into Monitor module.
  perf           CLI tool to view latest perf log of each...
  prefixmgr      CLI tool to peek into Prefix Manager module.```

**Comment by Vijayendra-Pretlist** [comment]
Hi 
I analysed this issue further , This seems to be a python version issue . I ran below commands 
cd openr/openr/py
python3 setup.py build
sudo python3 setup.py install

Then I installed thrift manually 
git clone https://github.com/apache/thrift.git
cd thrift/lib/py
sudo python3 setup.py install

Now I am getting following log
Traceback (most recent call last):
  File "/usr/local/bin/breeze", line 9, in <module>
    load_entry_point('py-openr==1.0', 'console_scripts', 'breeze')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/py_openr-1.0-py3.5.egg/openr/cli/breeze.py", line 22, in <module>
  File "/usr/local/lib/python3.5/dist-packages/py_openr-1.0-py3.5.egg/openr/cli/clis/config.py", line 14, in <module>
  File "/usr/local/lib/python3.5/dist-packages/py_openr-1.0-py3.5.egg/openr/cli/commands/config.py", line 11, in <module>
  File "/usr/local/lib/python3.5/dist-packages/py_openr-1.0-py3.5.egg/openr/AllocPrefix/ttypes.py", line 10, in <module>
ImportError: No module named 'thrift.util'


I am not able to resolve the dependency  named 'thrift.util'

**Comment by cenzhao** [comment]
looks like you installed apache/thrift, what you need is fbthrift. 

https://github.com/facebook/fbthrift
can you try it again?

**Comment by saifhhasan** [comment]
@Vijayendra-Pretlist - Were you able to resolve the issue by installing fbthrift ? Close the issue if issue is resolved.
